spring:
  application:
    name: cache-web
#  datasource:
#    url: jdbc:postgresql://localhost:5432/inventory
#    username: contact@suriyaprakhash.com
#    password: password
##    pool-size: 30
#    driver-class-name: org.postgresql.Driver

    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect